### PR TITLE
Simply updated to 1.8

### PR DESCRIPTION
**Pull request by scarabcoder**
Please notify me if you use player names in this plugin, so I can switch
to UUIDs.

### CODE REVIEW

**Comment by scarabcoder** [comment]
Also, I should add, that I didn't do anything except update changelog.txt. I'm not sure if you save player names; if you do, I can switch them to UUIDs.

You should just simply have to export the jar file again with this pull request merged, or use this jar file (exported from source):
https://www.dropbox.com/s/h10tm2lchhq0sqx/SyncChest.jar?dl=1

**Comment by AlexMl** [comment]
Thanks for your work. I will have a look on it, merge and upload the new version tomorrow.

**Comment by AlexMl** [comment]
Thanks for your work. I will have a look on it, merge and upload the new version tomorrow.

**Comment by AlexMl** [comment]
Thanks for your work. I will have a look on it, merge and upload the new version tomorrow.

**Comment by AlexMl** [comment]
Thanks for your work. I will have a look on it, merge and upload the new version tomorrow.

**Comment by AlexMl** [comment]
Thank you for your time, but changing the changelog to "support" 1.8 is not worth an update. Sorry.
Also this plugin does not save players at all, therefore does not need an uuid update.

**Pull request closed without merging**
